source 'https://rubygems.org'

gem 'rails', '5.1.0'

gem 'sass-rails' #,   '~> 3.2.3'
gem 'autoprefixer-rails'
gem 'better_errors'
gem 'binding_of_caller'
gem 'jquery-rails'
gem 'devise'
gem 'devise_invitable'
gem 'will_paginate'
gem 'kaminari'
gem 'simple_form', '~> 3.5.0'
gem 'guard'
gem 'guard-livereload'

gem 'rack-cache'
gem 'puma'

gem 'pg', :group => :production
gem 'thin', group: :production
gem 'rails_12factor', group: :production
gem 'heroku_rails_deflate', :group => :production

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'uglifier' #, '>= 1.0.3'
end

group :test do
  gem 'mocha'
end

group :development do
  gem 'sqlite3'
  gem 'rrt', :path => '../../'
end

