ruby '2.2.0'

source 'https://rubygems.org'

gem 'rails', '>= 3.2'
gem 'rake', '10.4.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'rack', '1.5.2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails' #, '~> 3.2.1'
  gem 'uglifier' #, '>= 1.0.3'
end

gem 'sass-rails' #,   '~> 3.2.3'
gem 'autoprefixer-rails'
gem 'better_errors'
gem 'binding_of_caller'
gem 'jquery-rails'
gem 'devise'
gem 'will_paginate'
gem 'kaminari'
gem 'simple_form', '~> 3.1.0.rc2', github: 'plataformatec/simple_form', branch: 'master', tag: 'v3.1.0.rc1'
gem 'guard'
gem 'guard-livereload'

group :test do
  gem 'mocha'
end

group :development do
  gem 'sqlite3'
  if ENV['DRESSSED_DEBUG']
    gem 'dresssed-ives', :path => '../../'
  end
end

gem 'pg', :group => :production
gem 'thin', group: :production
gem 'rails_12factor', group: :production

group :production do
   source 'http://dresssed.com/gems/263834bde09a27b4f271aeede0e37ed5' do
     gem 'dresssed-ives'
   end
end

